from pathlib import Path
p=Path('app/src/main/java/com/fabdata/app/BackupV3Support.kt')
s=p.read_text()
def r(a,b,m):
    global s
    if m in s:return
    if a not in s: raise SystemExit('missing '+m)
    s=s.replace(a,b,1)
r('        ForecastMemoryStore.ensure(db.writableDatabase)\n','        ForecastMemoryStore.ensure(db.writableDatabase)\n        ForecastLocalSnapshotStore.ensure(db.writableDatabase)\n','ForecastLocalSnapshotStore.ensure(db.writableDatabase)')
r('        db.readableDatabase.rawQuery(\n            """\n            SELECT reference_key, timestamp, temperature, humidity, source, confidence\n','        db.readableDatabase.rawQuery(\n            """\n            SELECT reference_key, issued_at, target_ts, baseline_temperature, fab_temperature, confidence, model_samples, created_at\n            FROM ${ForecastLocalSnapshotStore.TABLE}\n            ORDER BY reference_key, target_ts, issued_at\n            """.trimIndent(), null\n        ).use { c ->\n            while (c.moveToNext()) {\n                writeJson(writer, "FORECAST_LOCAL_ARCHIVE", JSONObject().apply {\n                    put("referenceKey", c.getString(0))\n                    put("issuedAt", c.getLong(1))\n                    put("targetAt", c.getLong(2))\n                    put("baselineTemperature", c.getDouble(3))\n                    put("fabTemperature", c.getDouble(4))\n                    putNullable("confidence", if (c.isNull(5)) null else c.getDouble(5))\n                    put("modelSamples", c.getInt(6))\n                    put("createdAt", c.getLong(7))\n                })\n            }\n        }\n\n        db.readableDatabase.rawQuery(\n            """\n            SELECT reference_key, timestamp, temperature, humidity, source, confidence\n','FORECAST_LOCAL_ARCHIVE')
r('                "FORECAST_ARCHIVE" -> restoreForecastArchive(json(values))\n                "WEATHER" -> restoreWeather(values)\n','                "FORECAST_ARCHIVE" -> restoreForecastArchive(json(values))\n                "FORECAST_LOCAL_ARCHIVE" -> restoreForecastLocalArchive(json(values))\n                "WEATHER" -> restoreWeather(values)\n','restoreForecastLocalArchive(json(values))')
r('    private fun restoreWeather(values: Map<String, String>) {\n','    private fun restoreForecastLocalArchive(o: JSONObject) {\n        val key = o.optString("referenceKey", "").trim()\n        val issuedAt = o.optLong("issuedAt", -1L)\n        val targetAt = o.optLong("targetAt", -1L)\n        val baseline = o.optDouble("baselineTemperature", Double.NaN)\n        val fab = o.optDouble("fabTemperature", Double.NaN)\n        if (key.isBlank() || issuedAt < 0L || targetAt < 0L || !baseline.isFinite() || !fab.isFinite()) return\n        ForecastLocalSnapshotStore.restore(db.writableDatabase, key, issuedAt, targetAt, baseline, fab, nullableDouble(o, "confidence"), o.optInt("modelSamples", 0), o.optLong("createdAt", issuedAt))\n    }\n\n    private fun restoreWeather(values: Map<String, String>) {\n','private fun restoreForecastLocalArchive')
p.write_text(s)
